import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { Rubik_Mono_One } from "next/font/google";
import type { Viewport } from "next";
import "@/styles/globals.css";

export const viewport: Viewport = {
  viewportFit: "cover",
};

const inter = Rubik_Mono_One({
  subsets: ["latin", "cyrillic"],
  variable: "--font-inter",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body className={inter.className}>
        <NextIntlClientProvider messages={messages}>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
