import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { Rubik_Mono_One, Open_Sans } from "next/font/google";
import type { Viewport } from "next";
import CookieConsentBanner from "@/components/cookie-consent-banner/Banner";
import { Ads } from "@/components/ads/Ads";

import "@/styles/globals.css";
import clsx from "clsx";

export const viewport: Viewport = {
  viewportFit: "cover",
};

const rubik = Rubik_Mono_One({
  subsets: ["latin", "cyrillic"],
  variable: "--font-rubik",
  weight: "400",
});

const openSans = Open_Sans({
  subsets: ["latin", "cyrillic"],
  variable: "--font-open-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const messages = await getMessages();
  return (
    <html lang={locale}>
      <body
        className={clsx(rubik.className, rubik.variable, openSans.variable)}
      >
        <NextIntlClientProvider messages={messages}>
          <CookieConsentBanner />
          {children}
          <Ads />
        </NextIntlClientProvider>
      </body>
      <script
        async
        src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-9529954302448484"
        crossOrigin="anonymous"
      ></script>
    </html>
  );
}
